### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by dmahak** [drmonkeyninja/cakephp-tmdb#2]
Hi Andy,

I followed installation instructions, but when I try to load my test page, I get the following cake error message :

Error: The application is trying to load a file from the CakeTmdb plugin.
Make sure your plugin CakeTmdb is in the E:\www\tmdb\plugins\ directory and was loaded. 

Look like something is missing in the release?

Thanks for your help,
Daniel

**Comment by drmonkeyninja** [comment]
The CakeTmdb plugin should be in your vendors directory, something like /vendor/drmonkeyninja/cakephp-tmdb, do you have this?

**Comment by dmahak** [comment]
Yes, that's what I have. The exact directory/files structure I get is the following :

.\vendor\drmonkeyninja\cakephp-tmdb

```
.editorconfig
composer.json
LICENSE
README.md
src
tests
```

.\vendor\drmonkeyninja\cakephp-tmdb\src\Lib\Tmdb\Tmdb.php

.\vendor\drmonkeyninja\cakephp-tmdb\src\View\Helper\TmdbHelper.php

.\vendor\drmonkeyninja\cakephp-tmdb\tests\TestCase\View\Helper\TmdbHelperTest.php

Nothing else. Only 2 php files in src/Lib and src/View and one in tests.

There's nothing called "CakeTmdb". How is it supposed to load the plugin with " Plugin::load('CakeTmdb'); " in my bootstrap.php ?

When I change the plugin load command to load('cakephp-tmdb'); or if a change the .vendor\vendor\drmonkeyninja\cakephp-tmdb directory name to .vendor\vendor\drmonkeyninja\CakeTmdb I get the same error

I also tried moving the drmonkeyninja\cakephp-tmdb to the .\plugins directory and renaming it CakeTmdb. It then goes a little bit further but I get the following fatal error :

Fatal error: Class 'CakeTmdb\Lib\Tmdb\Driver\Tmdb' not found in E:\www\tmdbtest\vendor\muffin\webservice\src\Connection.php on line 23

Error: Class 'CakeTmdb\Lib\Tmdb\Driver\Tmdb' not found
File E:\www\tmdbtest\vendor\muffin\webservice\src\Connection.php
Line: 23 

Any hint?
Thanks

**Comment by caesarius1187** [comment]
I´m on the same issue plz help!

**Comment by drmonkeyninja** [comment]
@caesarius1187 I've recently done a fresh install of this plugin and didn't encounter any issues. Could you confirm that you are using Composer to install and that you are using the most recent version (currently at `3.1.1`).

**Comment by caesarius1187** [comment]
yes I'm using composer in Windows 10, I don't know why this error show up, I think classes can't see each other in vendors file, or something like that

**Comment by caesarius1187** [comment]
![2018-09-03 11_23_26-error_ fatal error](https://user-images.githubusercontent.com/4308016/44991850-dd106200-af6b-11e8-8613-7550204f1ac6.png)

**Comment by caesarius1187** [comment]
@drmonkeyninja Maybe Connection is trying to find that class in Plugin folder and not in Vendor's

**Comment by drmonkeyninja** [comment]
@caesarius1187 what version of `muffin/webservice` have you installed? I have version `1.3.0` and [line 29](https://github.com/UseMuffin/Webservice/blob/1.3.0/src/Connection.php#L29) of the `Connection` class is a blank line.

**Comment by angelxmoreno** [comment]
A fresh install is also working for me. I used composer to install CakePHP and to install the app.

**Comment by drmonkeyninja** [comment]
I am closing this for now as installation seems to be working for people with the most recent version of the plugin. If the problem continues you're welcome to open a new issue with more details about how to recreate the problem.
